ALTER TABLE PARTSUPP
ADD CONSTRAINT partsupp_part_fkey
   FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY);

ALTER TABLE PARTSUPP
ADD CONSTRAINT partsupp_supplier_fkey
   FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY);

ALTER TABLE CUSTOMER
ADD CONSTRAINT customer_nation_fkey
   FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY);

ALTER TABLE ORDERS
ADD CONSTRAINT orders_customer_fkey
   FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY);

ALTER TABLE LINEITEM
ADD CONSTRAINT lineitem_orders_fkey
   FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY);

ALTER TABLE LINEITEM
ADD CONSTRAINT lineitem_parts_fkey
   FOREIGN KEY (L_PARTKEY) REFERENCES PART(P_PARTKEY);

ALTER TABLE LINEITEM
ADD CONSTRAINT lineitem_suppliers_fkey
   FOREIGN KEY (L_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY);

ALTER TABLE LINEITEM
ADD CONSTRAINT lineitem_partsupp_fkey
   FOREIGN KEY (L_PARTKEY,L_SUPPKEY)
    REFERENCES PARTSUPP(PS_PARTKEY,PS_SUPPKEY);

ALTER TABLE NATION
ADD CONSTRAINT nation_region_fkey
   FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY);

CREATE INDEX psidxp on partsupp (ps_partkey);
CREATE INDEX psidxs on partsupp (ps_suppkey);
CREATE INDEX cidxn on customer (c_nationkey);
CREATE INDEX oidxc on orders (o_custkey);
CREATE INDEX lidxo on lineitem (l_orderkey);
CREATE INDEX lidxp on lineitem (l_partkey);
CREATE INDEX lidxs on lineitem (l_suppkey);
CREATE INDEX lidxps on lineitem (l_partkey, l_suppkey);
CREATE INDEX lidxn on nation (n_regionkey);